import streamlit as st
import cv2
import numpy as np
from data_loader import load_data, save_data, recalc_percentages, write_attendance, is_saturday
from datetime import date

st.title("QR Check-In")
st.caption("Point the camera at a member's QR code — it will be detected automatically when you capture.")

# ----------------------------
# Date + optional meeting
# ----------------------------
opt_col, date_col = st.columns([1, 2])

with opt_col:
    is_optional = st.toggle("Optional Meeting", value=False,
                            help="Absent members get O (no % deduction) instead of A.")
with date_col:
    selected_date = st.date_input("Meeting date", value=date.today())

date_str = selected_date.strftime("%m/%d/%y")

if is_optional:
    st.caption(f"Optional meeting — unscanned members will be marked **O** for {date_str}")
else:
    st.caption(f"Regular meeting — unscanned members will be marked **A** for {date_str}")

if is_saturday(date_str):
    st.caption(f"🗓️ {date_str} is a **Saturday** (double session) — attendance will be recorded in two columns and count twice.")

st.divider()

# ----------------------------
# Session state
# ----------------------------
if "checked_in" not in st.session_state:
    st.session_state.checked_in = set()

# ----------------------------
# Camera + QR decode
# ----------------------------
st.subheader("Scan a QR Code")
st.caption("Take a photo with the member's QR code in frame — it will decode instantly.")

img_file = st.camera_input("", label_visibility="collapsed")

if img_file is not None:
    file_bytes = np.frombuffer(img_file.read(), np.uint8)
    img = cv2.imdecode(file_bytes, cv2.IMREAD_COLOR)
    detector = cv2.QRCodeDetector()
    data, _, _ = detector.detectAndDecode(img)

    if data:
        prefix = "ROBOLOCO:"
        if data.startswith(prefix):
            name = data[len(prefix):].strip()
            if name not in st.session_state.checked_in:
                st.session_state.checked_in.add(name)
                st.success(f"✅ {name} checked in!")
            else:
                st.info(f"{name} is already checked in.")
        else:
            st.warning("Unrecognized QR code — use codes generated by this app.")
    else:
        st.error("No QR code detected. Try getting closer or improving lighting.")

# ----------------------------
# Live check-in list
# ----------------------------
st.divider()
checked_in_list = sorted(st.session_state.checked_in)
st.subheader(f"Checked In ({len(checked_in_list)})")

if checked_in_list:
    for name in checked_in_list:
        st.write(f"✅ {name}")
else:
    st.caption("No one checked in yet.")

if checked_in_list:
    with st.expander("Remove a mis-scan"):
        to_remove = st.selectbox("Select member to remove", checked_in_list, key="remove_select")
        if st.button("Remove"):
            st.session_state.checked_in.discard(to_remove)
            st.rerun()

# ----------------------------
# Submit attendance
# ----------------------------
st.divider()
if st.button("Submit Attendance", type="primary"):
    if not st.session_state.checked_in:
        st.warning("No one has checked in yet.")
    else:
        fresh_df = load_data()
        absent_code = "O" if is_optional else "A"

        matched, unrecognized = write_attendance(
            fresh_df, date_str, st.session_state.checked_in, absent_code
        )
        fresh_df = recalc_percentages(fresh_df)

        if save_data(fresh_df):
            st.success(f"✅ Attendance saved for {date_str}! {matched} present.")
            st.session_state.checked_in = set()

        if unrecognized:
            st.warning(f"These scanned names weren't in the roster: {', '.join(unrecognized)}")
